"use client";
// Standalone concept page body (behind the gate), in the same frame as the
// journal and glossary item pages: back link, share, the concept, previous/next.
import Link from "next/link";
import { useEffect } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import ItemHeader from "@/components/ItemHeader";
import Footer from "@/components/Footer";
import ShareMenu from "@/components/ShareMenu";
import ConceptArticle from "@/components/ConceptArticle";
import DisclaimerLink from "@/components/DisclaimerLink";
import { CONCEPTS } from "@/lib/concepts";
import { track } from "@/lib/analytics";
import BottomSections from "@/components/BottomSections";

type Nav = { id: string; title: string };

export default function ConceptItemReader({ id, n, prev, next }: { id: string; n: number; prev?: Nav; next?: Nav }) {
  const c = CONCEPTS.find((x) => x.id === id)!;
  useEffect(() => { track("concept_opened", { id, route: true }); }, [id]);
  return (
    <div className="min-h-screen flex flex-col bg-background text-foreground">
      <ItemHeader />
      <main className="flex-1 w-full max-w-[1400px] mx-auto px-4 sm:px-6 py-6">
        <div className="flex items-center justify-between mb-8">
          <Link href="/concepts" className="text-sm text-accent inline-flex items-center gap-1"><ChevronLeft size={15} /> Back to concepts</Link>
          <ShareMenu title={`${c.title} — Invisible Ships`} align="right" />
        </div>
        {/* Same framing as the Concepts page's sentence (Sean, 30 Sep 2026). */}
        <p className="body-copy max-sm:text-[17px] max-sm:leading-[1.55] text-foreground/85 measure m-0 mb-10">
          An idea drawn from this archive&rsquo;s research and journal, either the author&rsquo;s own speculation or
          generated by AI, and labelled as such.{" "}
          <DisclaimerLink from="concept_page" className="text-accent underline underline-offset-4 whitespace-nowrap">
            Read the disclaimer
          </DisclaimerLink>
        </p>
        <ConceptArticle c={c} n={n} />
        <nav aria-label="More concepts" className="flex gap-6 mt-14 pt-6 border-t border-edge">
          {prev ? (
            <Link href={`/concepts/${prev.id}`} className="text-accent text-sm inline-flex items-start gap-1 max-w-[45%]">
              <ChevronLeft size={15} className="mt-0.5 shrink-0" /> <span>{prev.title}</span>
            </Link>
          ) : <span />}
          {next && (
            <Link href={`/concepts/${next.id}`} className="text-accent text-sm ml-auto inline-flex items-start gap-1 text-right max-w-[45%]">
              <span>{next.title}</span> <ChevronRight size={15} className="mt-0.5 shrink-0" />
            </Link>
          )}
        </nav>
        {/* The home page's other sections, never this one (Sean, 1 Oct 2026). */}
        <BottomSections exclude={["concepts"]} from="concept" />
      </main>
      <Footer />
    </div>
  );
}
