"use client";
// Standalone concept page body (behind the gate), in the same frame as the
// journal and glossary item pages: back link, share, the concept, previous/next.
import Link from "next/link";
import { useEffect } from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import ItemHeader from "@/components/ItemHeader";
import Footer from "@/components/Footer";
import ShareMenu from "@/components/ShareMenu";
import ConceptArticle from "@/components/ConceptArticle";
import SideNav from "@/components/SideNav";
import { useRouter } from "next/navigation";
import PageIntro from "@/components/PageIntro";
import { BASIS_LABEL, CONCEPTS, ORIGIN_LABEL, SERIES, plainText } from "@/lib/concepts";
import { track } from "@/lib/analytics";
import BottomSections, { Block, ConceptCards } from "@/components/BottomSections";
import { THEMES } from "@/lib/themes";

type Nav = { id: string; title: string };

export default function ConceptItemReader({ id, n, prev, next }: { id: string; n: number; prev?: Nav; next?: Nav }) {
  const c = CONCEPTS.find((x) => x.id === id)!;
  useEffect(() => { track("concept_opened", { id, route: true }); }, [id]);
  const router = useRouter();
  const series = c.series ? SERIES[c.series] : undefined;
  // The series as concept tiles, in reading order, built the way the bottom
  // sections build theirs (lib/home-sections.ts conceptTiles).
  const seriesTiles = (series?.ids ?? []).flatMap((sid) => {
    const k = CONCEPTS.findIndex((x) => x.id === sid);
    if (k < 0) return [];
    const s = CONCEPTS[k];
    return [{ id: s.id, n: k + 1, origin: ORIGIN_LABEL[s.origin], basis: BASIS_LABEL[s.basis], title: s.title,
      body: plainText(s.body).slice(0, 1400), topics: s.topics.slice(0, 3).map((t) => THEMES[t] ?? t) }];
  });
  const seriesPos = series ? series.ids.indexOf(c.id) : -1;
  const nextId = series ? series.ids[(seriesPos + 1) % series.ids.length] : c.id;
  const nextInSeries = CONCEPTS.find((x) => x.id === nextId) ?? c;
  return (
    <div className="min-h-screen flex flex-col bg-background text-foreground">
      <ItemHeader />
      <main className="flex-1 w-full max-w-[1400px] mx-auto px-4 sm:px-6 py-6">
        {/* TITLE BAND, IDENTICAL TO THE CONCEPTS LIST PAGE (Sean, 4 Oct 2026: "it
            needs to match the height and the top margin from the header
            exactly"): the same band as JournalBrowser's TitleBand, 72px on a
            phone and 160px from 640px, H1 at its foot, same type. The back link
            sits in the eyebrow slot and Share in the actions slot, so neither
            pushes the title down. */}
        <section className="w-full min-h-[72px] sm:min-h-[160px] flex flex-wrap items-end justify-between gap-x-6 gap-y-4 mb-4 pb-0 sm:mb-8 sm:pb-6">
          <div>
            <p className="font-display text-[12px] sm:text-[13px] font-semibold uppercase tracking-[0.14em] m-0 mb-2 sm:mb-3">
              <Link href="/concepts" className="text-muted hover:text-foreground inline-flex items-center gap-1"><ChevronLeft size={14} /> Concepts</Link>
            </p>
            <h1 className="font-display font-bold tracking-tight text-foreground text-[25px] md:text-[34px] lg:text-[42px] leading-none">{c.title}</h1>
          </div>
          <ShareMenu title={`${c.title} — Invisible Ships`} align="right" />
        </section>

        {/* Number and labels under the H1, then the page description, as the
            News and Concepts pages place theirs. */}
        <div className="flex flex-wrap items-baseline gap-x-4 gap-y-2 mb-5">
          <span className="text-[13px] uppercase tracking-[0.08em] font-semibold text-muted tabular-nums">
            {String(n).padStart(2, "0")}
          </span>
          {/* Origin reads first — who formed a claim before what it rests on. */}
          <span className="text-[13px] uppercase tracking-[0.08em] font-semibold text-background bg-foreground px-2.5 py-1">
            {ORIGIN_LABEL[c.origin]}
          </span>
          <span className="text-[13px] uppercase tracking-[0.08em] font-semibold text-foreground">
            {BASIS_LABEL[c.basis]}
          </span>
        </div>
        <PageIntro from="concept_page">
          An idea drawn from this archive&rsquo;s research and journal, either the author&rsquo;s own speculation or
          generated by AI, and labelled as such.
        </PageIntro>

        {/* A concept in a series gets a right-hand rail titled "Series", the same
            SideNav the Glossary and Journal use, mirrored to the right (Sean,
            4 Oct 2026: "that sidebar styling needs to match the left-hand
            sidebar for glossary… on the right-hand side… title it series").
            A concept without a series keeps its single column. */}
        {series ? (
          <div className="lg:grid lg:grid-cols-[minmax(0,1fr)_minmax(15rem,25%)] lg:gap-x-16 lg:items-start">
            <div className="lg:order-2">
              <SideNav
                large
                mode="index"
                label="Series"
                sections={series.ids.flatMap((sid, k) => {
                  const s = CONCEPTS.find((x) => x.id === sid);
                  return s ? [{ id: sid, label: `${k + 1}. ${s.title}` }] : [];
                })}
                active={c.id}
                onPick={(sid) => { if (sid !== c.id) router.push(`/concepts/${sid}`); }}
              />
            </div>
            <div className="min-w-0 lg:order-1"><ConceptArticle c={c} /></div>
          </div>
        ) : (
          <ConceptArticle c={c} />
        )}
        {/* SERIES, AS A BOTTOM SECTION (Sean, 4 Oct 2026: "let's use this bottom
            section immediately under the concept to run two up tiles… call it
            series… use the existing bottom section architecture"). The same
            Block and two-up concept cards as the Concepts bottom section, in
            the series' reading order. A concept with no series keeps its
            previous / next links. */}
        {series ? (
          <div className="mt-16">
            <Block id="series" from="concept" eyebrow="Series" wide
              heading={series.title}
              href={`/concepts/${nextInSeries.id}`}
              label={nextInSeries.id === c.id ? "Start the series" : (seriesPos < series.ids.length - 1 ? `Next in the series: ${nextInSeries.title}` : `Back to the start: ${nextInSeries.title}`)}>
              <p className="body-copy text-foreground/85 measure m-0 mb-8">{series.blurb}</p>
              <ConceptCards tiles={seriesTiles} from="concept-series" label={`Series: ${series.title}`} />
            </Block>
          </div>
        ) : (
        <nav aria-label="More concepts" className="flex gap-6 mt-14 pt-6 border-t border-edge">
          {prev ? (
            <Link href={`/concepts/${prev.id}`} className="text-accent text-sm inline-flex items-start gap-1 max-w-[45%]">
              <ChevronLeft size={15} className="mt-0.5 shrink-0" /> <span>{prev.title}</span>
            </Link>
          ) : <span />}
          {next && (
            <Link href={`/concepts/${next.id}`} className="text-accent text-sm ml-auto inline-flex items-start gap-1 text-right max-w-[45%]">
              <span>{next.title}</span> <ChevronRight size={15} className="mt-0.5 shrink-0" />
            </Link>
          )}
        </nav>
        )}
        {/* The home page's other sections, never this one (Sean, 1 Oct 2026). */}
        <BottomSections exclude={["concepts"]} from="concept" />
      </main>
      <Footer />
    </div>
  );
}
