"use client";
// GENERATED by scripts/build_govcloud_report.py — do not edit by hand.
// Source: report-src/gov-cloud-dashboard.html
//
// The report renders natively in the page (no iframe). Its CSS is scoped under
// .gov-report so it cannot collide with globals.css in either direction, its
// palette is rebound to the site's monochrome tokens, and its drawing script is
// loaded from /reports/gov-cloud-report.js on mount — innerHTML never executes
// scripts, so it has to be injected deliberately.
import { useEffect } from "react";

const CSS = `.gov-report{
  --surface-1: transparent;
  --surface-2: rgb(var(--panel));
  --text-primary: rgb(var(--foreground));
  --text-secondary: rgb(var(--muted));
  --text-muted: rgb(var(--muted));
  --grid: rgb(var(--edge));
  --warn: rgb(var(--foreground));
  --heat: var(--foreground);
  --series-1: #1f1f1f; --series-2: #4f4f4f; --series-3: #878787;
  --series-4: #b6b6b6; --series-5: #dddddd; --series-6: #6b6b6b;
}
html.dark .gov-report{
  --surface-1: transparent;
  --surface-2: rgb(var(--panel));
  --text-primary: rgb(var(--foreground));
  --text-secondary: rgb(var(--muted));
  --text-muted: rgb(var(--muted));
  --grid: rgb(var(--edge));
  --warn: rgb(var(--foreground));
  --heat: var(--foreground);
  --series-1: #f1f1f1; --series-2: #b6b6b6; --series-3: #878787;
  --series-4: #595959; --series-5: #343434; --series-6: #a3a3a3;
}
.gov-report *{box-sizing:border-box}
.gov-report{font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;font-size:14px;line-height:1.5}
.gov-report .wrap{max-width:none;margin:0 auto;padding:24px 20px 64px}
.gov-report h1{font-size:21px;margin:0 0 2px}
.gov-report .sub{color:var(--text-secondary);font-size:13px;margin:0 0 14px}
.gov-report .tabs{display:flex;gap:6px;margin:8px 0 6px;flex-wrap:wrap}
.gov-report .tab{font:inherit;font-weight:600;color:var(--text-secondary);background:none;border:none;border-bottom:2px solid transparent;padding:8px 9px;cursor:pointer}
.gov-report .tab.on{color:var(--text-primary);border-bottom-color:var(--series-1)}
.gov-report .bar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:12px 0 20px}
.gov-report button.ctl, .gov-report select{font:inherit;color:var(--text-primary);background:var(--surface-2);border:1px solid var(--grid);border-radius:8px;padding:7px 12px;cursor:pointer}
.gov-report button.ctl.on{background:var(--series-1);color:#fff;border-color:var(--series-1)}
.gov-report .tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:24px}
.gov-report .tile{background:var(--surface-2);border:1px solid var(--grid);border-radius:12px;padding:14px 16px}
.gov-report .tile .n{font-size:25px;font-weight:700;letter-spacing:-.5px}
.gov-report .tile .l{color:var(--text-secondary);font-size:12px;margin-top:2px}
.gov-report h2{font-size:15px;margin:26px 0 10px}
.gov-report .card{background:var(--surface-2);border:1px solid var(--grid);border-radius:12px;padding:16px;overflow:auto}
.gov-report .hm{border-collapse:separate;border-spacing:2px}
.gov-report .hm th{font-weight:600;color:var(--text-secondary);font-size:11px;text-align:left;padding:2px 4px}
.gov-report .hm thead th{writing-mode:vertical-rl;transform:rotate(180deg);height:96px;vertical-align:bottom}
.gov-report .hm td{width:26px;height:24px;text-align:center;border-radius:4px;font-size:10px;color:#fff;font-variant-numeric:tabular-nums}
.gov-report .hm td.z{color:var(--text-muted);background:transparent!important}
.gov-report .legend{display:flex;gap:16px;flex-wrap:wrap;font-size:12px;color:var(--text-secondary);margin:8px 2px}
.gov-report .sw{display:inline-block;width:12px;height:12px;border-radius:3px;vertical-align:-1px;margin-right:5px}
.gov-report .hbars{display:flex;flex-direction:column;gap:6px}
.gov-report .hrow{display:grid;grid-template-columns:150px 1fr 70px;align-items:center;gap:8px;font-size:12px}
.gov-report .track{background:var(--surface-1);border-radius:5px;height:18px;overflow:hidden}
.gov-report .fill{height:100%;border-radius:5px}
.gov-report .tl{display:flex;align-items:flex-end;gap:10px;height:170px;padding:8px 4px 0}
.gov-report .tlcol{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;gap:4px;height:100%}
.gov-report .tlbar{width:70%;background:var(--series-1);border-radius:4px 4px 0 0;min-height:2px}
.gov-report .tllab{font-size:11px;color:var(--text-secondary)}
.gov-report .tlval{font-size:11px}
.gov-report .dt{width:100%;font-size:12px}
.gov-report .dt th, .gov-report .dt td{border-bottom:1px solid var(--grid);padding:5px 7px;text-align:left;vertical-align:top}
.gov-report .dt th{position:sticky;top:0;background:var(--surface-2)}
.gov-report .pill{display:inline-block;padding:1px 7px;border-radius:20px;font-size:11px;border:1px solid var(--grid)}
.gov-report .emg{color:var(--series-2);font-weight:600}
.gov-report .tierA{color:#008300}
.gov-report .tierB{color:var(--series-1)}
.gov-report .tierC{color:var(--series-2)}
.gov-report #tip{position:fixed;pointer-events:none;background:var(--surface-1);border:1px solid var(--grid);border-radius:8px;padding:8px 10px;font-size:12px;max-width:300px;box-shadow:0 4px 18px rgba(0,0,0,.18);opacity:0;transition:opacity .08s;z-index:9}
.gov-report .hidden{display:none}
.gov-report .foot{color:var(--text-muted);font-size:11px;margin-top:26px}
.gov-report .note{color:var(--text-muted);font-size:12px;margin:6px 2px}
.gov-report .callout{background:var(--surface-1);border:1px solid var(--grid);border-left:3px solid var(--series-2);border-radius:8px;padding:10px 12px;font-size:12.5px;margin:10px 0}

/* --- container: no inner shell -------------------------------------------
   The report shipped as a standalone page, so it carried its own 1180px
   centred wrapper with page padding. Inside the site it must add nothing:
   the site's <main> already sets the width and gutters. */
.gov-report .wrap { max-width: none !important; margin: 0 !important; padding: 0 !important; }
.gov-report { background: none !important; }
.gov-report .card, .gov-report .tile, .gov-report .track { background: none !important; }
.gov-report .dt th { background: none !important; }

/* --- type: the site's faces and scale ------------------------------------ */
.gov-report { font-family: var(--font-sans), ui-sans-serif, system-ui, sans-serif; font-size: 15px; }
.gov-report h1, .gov-report h2, .gov-report .tile .n {
  font-family: var(--font-display), var(--font-sans), sans-serif;
  font-weight: 600; letter-spacing: -0.01em;
}
/* The page already renders an <h1> ("Data") in the TitleBand, so the report's own
   title is demoted — one h1 per page. */
/* Header consolidation: the page's TitleBand already renders "Data" as the h1,
   and DataView no longer prints a standfirst, so the report's own long title is
   hidden and its stats subline becomes the single header line. */
.gov-report h1 { display: none; }
.gov-report .sub { margin: 0 0 20px; }
/* The control row is empty except on Timeline/Capabilities, where it holds the
   domain and category selects; collapse its spacing so it leaves no gap. */
.gov-report .bar { margin: 0; gap: 12px; }
.gov-report .bar:not(:has(> span:not(.hidden))) { margin: 0; min-height: 0; }
.gov-report h2 { font-size: 21px; margin: 40px 0 14px; }
.gov-report .tile .n { font-size: 34px; }
/* Prose takes the site's reading serif at the site's body size. Tables, legends
   and axis labels stay functional sizes in the site sans — 22px would break the
   dense registers and the heatmap. */
.gov-report .sub, .gov-report .note, .gov-report .callout {
  font-family: var(--font-serif), Georgia, serif; font-size: 22px; line-height: 1.5;
}
.gov-report .callout { border-left: 2px solid rgb(var(--edge)); background: none !important; }
/* Axis and series labels shipped at 10-12px, sized for a dense standalone page.
   At the site's scale they were unreadable, so every label class steps up. */
.gov-report .dt { font-size: 15px; }
.gov-report .legend, .gov-report .foot, .gov-report .pill,
.gov-report .tile .l { font-size: 14px; }
.gov-report .hrow, .gov-report .tllab, .gov-report .tlval { font-size: 15px; }
.gov-report .hm th, .gov-report .hm td { font-size: 14px; }
.gov-report .hm th { font-weight: 600; padding: 4px 6px; }
/* Timeline + bar-chart text drawn inside SVG carries its own font-size attribute,
   which CSS must override explicitly to win. */
.gov-report svg text { font-size: 14px !important; }

/* --- vertical rhythm -----------------------------------------------------
   The report was laid out tight for a dense standalone page (5-8px paddings,
   6-24px margins). On the site it needs room to breathe, so every structural
   element gets vertical space. Applies to all six sub-pages. */
.gov-report .tabs { gap: 18px; margin: 0 0 28px; padding: 0 0 8px; }
.gov-report .bar { margin: 0 0 8px; }
.gov-report .tiles { gap: 34px 28px; margin: 0 0 52px; }
.gov-report h2 { margin: 56px 0 20px; }
.gov-report .card { margin: 0 0 16px; }
.gov-report .legend { gap: 22px; margin: 0 0 22px; }
.gov-report .note { margin: 0 0 20px; }
.gov-report .callout { margin: 32px 0; padding: 18px 0 18px 20px; }
.gov-report .dt th, .gov-report .dt td { padding: 14px 12px; }
.gov-report .hbars { gap: 14px; }
.gov-report .hrow { grid-template-columns: 190px 1fr 80px; gap: 14px; }
.gov-report .track { height: 22px; }
.gov-report .hm td { height: 38px; }
.gov-report .hm th { padding: 8px 6px; }
.gov-report .tl { height: 210px; padding: 16px 4px 0; gap: 14px; }
.gov-report .foot { margin-top: 48px; }

/* --- click modal ---------------------------------------------------------
   Hover gives a quick read; clicking a cell opens this, which is where the
   evidence lives — every deployment with its source, opening in a new tab. */
#gov-modal { position: fixed; inset: 0; z-index: 80; display: none; }
#gov-modal.on { display: block; }
#gov-modal .gm-back { position: absolute; inset: 0; background: rgb(var(--foreground) / 0.55); }
#gov-modal .gm-panel {
  position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);
  width: min(760px, calc(100vw - 48px)); max-height: calc(100vh - 96px); overflow-y: auto;
  background: rgb(var(--background)); color: rgb(var(--foreground));
  border: 2px solid rgb(var(--foreground)); padding: 36px 40px 40px;
}
#gov-modal .gm-x {
  position: absolute; top: 18px; right: 20px; background: none; border: none;
  font-family: var(--font-sans), sans-serif; font-size: 14px; text-transform: uppercase;
  letter-spacing: .06em; color: rgb(var(--muted)); cursor: pointer;
}
#gov-modal .gm-x:hover { color: rgb(var(--foreground)); }
#gov-modal h3 {
  font-family: var(--font-display), sans-serif; font-size: 30px; font-weight: 600;
  margin: 0 0 6px; letter-spacing: -0.01em;
}
#gov-modal .gm-count, #gov-modal .gm-load {
  font-family: var(--font-serif), Georgia, serif; font-size: 20px; color: rgb(var(--muted)); margin: 0 0 26px;
}
#gov-modal .gm-list { list-style: none; margin: 0; padding: 0; }
#gov-modal .gm-list li {
  display: flex; flex-wrap: wrap; align-items: baseline; gap: 10px 18px;
  padding: 16px 0; border-bottom: 1px solid rgb(var(--edge));
}
#gov-modal .gm-v { font-family: var(--font-sans), sans-serif; font-size: 18px; font-weight: 600; }
#gov-modal .gm-meta { font-family: var(--font-sans), sans-serif; font-size: 15px; color: rgb(var(--muted)); }
#gov-modal .gm-src {
  margin-left: auto; font-family: var(--font-sans), sans-serif; font-size: 15px;
  color: rgb(var(--foreground)); text-decoration: underline; text-underline-offset: 3px;
  display: inline-flex; align-items: baseline; gap: 10px;
}
#gov-modal .gm-tier {
  font-size: 13px; letter-spacing: .04em; text-transform: uppercase;
  color: rgb(var(--muted)); text-decoration: none;
}

/* --- hover layer ---------------------------------------------------------
   The report relied on native title="" tooltips, which the browser renders at a
   fixed ~12px and which cannot carry markup. #tip existed but was never filled.
   The enhancement script below moves each title into data-tip (suppressing the
   native bubble) and renders it here at the site's body size — roughly double. */
/* The report's showTip() sets style.opacity — so this must NOT use display:none,
   or opacity can never reveal it. That mismatch is what hid the hover entirely. */
.gov-report #tip {
  position: fixed; z-index: 60; opacity: 0; pointer-events: none;
  transition: opacity .12s ease;
  max-width: 520px; padding: 14px 18px;
  background: rgb(var(--background)); color: rgb(var(--foreground));
  border: 1px solid rgb(var(--edge));
  font-family: var(--font-serif), Georgia, serif; font-size: 22px; line-height: 1.4;
  box-shadow: 0 2px 18px rgb(var(--foreground) / 0.12);
}

.gov-report #tip .src { display: block; margin-top: 10px; font-family: var(--font-sans), sans-serif;
  font-size: 15px; color: rgb(var(--muted)); }
.gov-report svg rect, .gov-report .tlbar { shape-rendering: crispEdges; }

/* --- flat, borderless, square: match the site ----------------------------
   The report shipped as cards — 1px borders and 8-12px radii. The site is
   borderless with every radius forced to 0 in tailwind.config, so strip both. */
.gov-report .tile, .gov-report .card { border: none !important; }
/* Borderless, but the metric tiles still need to read as blocks — so they keep a
   theme-aware surface (--panel: #f5f5f5 light / #151515 dark) and their padding.
   Charts sit flush with no card padding. */
/* Stat tiles carry no data in their background, so under the stark B/W rule they
   carry no background at all — the number and its label do the work. Only marks
   whose fill ENCODES a value keep one (heatmap cells, bar fills). */
.gov-report .tile { background: none !important; padding: 0 !important; }
.gov-report .card { background: none !important; padding: 0 !important; }
.gov-report .track { background: rgb(var(--foreground) / 0.10) !important; }
.gov-report .card { overflow-x: auto; overflow-y: visible; }

.gov-report * { border-radius: 0 !important; }
.gov-report button.ctl, .gov-report select, .gov-report .pill, .gov-report #tip {
  border: 1px solid rgb(var(--edge)) !important;
}
.gov-report .callout { border: none !important; border-left: 2px solid rgb(var(--edge)) !important; }

/* --- adoption heatmap ---------------------------------------------------
   Cells are painted rgba(ink, 0.18-1.0) by count, so the fill IS the data and the
   gradation must survive intact — an earlier uniform ink overlay crushed that
   range to 0.63-1.0 and every cell looked alike. Nothing is overlaid now.

   Digit contrast is handled per-cell in the enhancement script instead: it reads
   each cell's alpha and picks surface-on-ink or ink-on-surface, so numbers stay
   legible at both ends of the ramp in both themes. */
.gov-report .hm { width: 100%; table-layout: fixed; }
.gov-report .hm td {
  width: auto; height: 38px;
  font-weight: 700; font-variant-numeric: tabular-nums;
  cursor: pointer;
}
.gov-report .hm td:not(.z):hover { outline: 2px solid rgb(var(--foreground)); outline-offset: -2px; }
.gov-report .hm td.z { cursor: default; }
/* Crosshair: hovering a cell marks its row and column headers, so the value can
   never be misattributed to the wrong domain — the failure mode when 21 columns
   share one grid. */
.gov-report .hm th.xh {
  color: rgb(var(--background)) !important;
  background: rgb(var(--foreground)) !important;
}
.gov-report .hm td.xh-cell { outline: 2px solid rgb(var(--foreground)); outline-offset: -2px; }

/* --- adoption grid: mobile alternative -----------------------------------
   A 21-column x 28-row matrix cannot be made legible on a phone by scaling —
   it needs a different form. Below 900px the grid is replaced by a stacked
   list: one block per geography, its domains ranked by count, each row a
   tappable bar that opens the same detail modal. Same data, same interaction,
   linear instead of tabular. */
.gov-report .hmm { display: none; }
@media (max-width: 900px) {
  .gov-report .hm { display: none; }
  .gov-report .hmm { display: block; }
}
.gov-report .hmm-geo {
  display: flex; align-items: baseline; justify-content: space-between; gap: 16px;
  margin: 32px 0 12px; padding-bottom: 8px;
  border-bottom: 1px solid rgb(var(--edge));
}
.gov-report .hmm-geo b { font-family: var(--font-display), sans-serif; font-size: 19px; font-weight: 600; }
.gov-report .hmm-geo span { font-size: 15px; color: rgb(var(--muted)); }
.gov-report .hmm ul { list-style: none; margin: 0; padding: 0; }
.gov-report .hmm li { margin: 0 0 8px; }
.gov-report .hmm button {
  width: 100%; display: grid; grid-template-columns: 1fr auto; align-items: center;
  gap: 12px; background: none; border: none; padding: 10px 0; cursor: pointer;
  font-family: var(--font-sans), sans-serif; font-size: 16px; text-align: left;
  color: rgb(var(--foreground));
}
.gov-report .hmm .hmm-bar { grid-column: 1 / -1; height: 10px; }
.gov-report .hmm .hmm-n { font-weight: 700; font-variant-numeric: tabular-nums; }
/* 21 domain columns in a fixed-layout table give ~50px each — nowhere near
   enough for labels like "defence-intel", which previously overflowed into their
   neighbours and made the whole grid unreadable. Rotate the column headers so the
   full name is legible and the columns can stay narrow. */
.gov-report .hm thead th {
  writing-mode: vertical-rl; transform: rotate(180deg);
  height: 165px; vertical-align: bottom; text-align: left;
  white-space: nowrap; padding: 6px 2px; font-size: 14px;
  color: rgb(var(--foreground));
}
.gov-report .hm thead th:first-child { writing-mode: horizontal-tb; transform: none; width: 108px; }
.gov-report .hm tbody th {
  writing-mode: horizontal-tb; transform: none; text-align: left;
  font-size: 14px; padding: 0 10px 0 0; white-space: nowrap;
  color: rgb(var(--foreground));
}
`;
const MARKUP = `<div class="wrap">
<h1>Government Cloud — Adoption · Procurement · Timeline · Investment · Litigation · Capabilities</h1>
<p class="sub">Prompts 1&ndash;6 · research date 2026-08-17 · 399 deployments · 90 awards · 99 regulations · 311 timeline milestones · 81 investment rows · 46 lawsuits · 73 platform capabilities · 660 sources · 34 geographies. Tier C = claimed/theoretical.</p>
<div class="tabs">
 <button class="tab on" data-t="adopt">Adoption map</button><button class="tab" data-t="proc">Procurement</button>
 <button class="tab" data-t="time">Timeline</button><button class="tab" data-t="invest">Investment</button>
 <button class="tab" data-t="lit">Litigation</button><button class="tab" data-t="cap">Capabilities</button></div>
<div class="bar">
 <span id="domWrap" class="hidden">Domain: <select id="domSel"><option value="">all</option></select></span>
 <span id="catWrap" class="hidden">Category: <select id="catSel"><option value="">all</option></select></span>
 </div>

<div id="adopt"><div class="tiles" id="a_tiles"></div><h2>Deployments by geography &times; mission domain</h2><div class="card"><table class="hm" id="heat"></table></div>
 <h2>Top vendors by deployment count</h2><div class="legend"><span><span class="sw" style="background:var(--series-1)"></span>hyperscaler</span><span><span class="sw" style="background:var(--series-2)"></span>local/champion</span><span><span class="sw" style="background:var(--series-3)"></span>ISV/platform</span></div><div class="card"><div class="hbars" id="vbars"></div></div></div>

<div id="proc" class="hidden"><div class="tiles" id="p_tiles"></div><h2>Disclosed award / pledge value by geography</h2><p class="note">Mixed basis: ceilings + pledges + projected savings. Not a market size.</p><div class="card"><div class="hbars" id="pgbars"></div></div>
 <h2>Awards by year announced</h2><div class="card"><div class="tl" id="tline"></div></div><h2>Re-compete calendar &mdash; next 36 months</h2><div class="card"><div class="hbars" id="rcbars"></div></div></div>

<div id="time" class="hidden"><div class="tiles" id="t_tiles"></div><h2>Master timeline &mdash; all threads</h2>
 <div class="legend"><span><span class="sw" style="background:var(--series-2)"></span>Law (A)</span><span><span class="sw" style="background:var(--series-1)"></span>Release (B)</span><span><span class="sw" style="background:var(--series-3)"></span>Deploy/enforcement (C)</span><span><span class="sw" style="background:var(--series-4)"></span>Litigation (D)</span><span><span class="sw" style="background:var(--series-5)"></span>Investment (E)</span><span style="color:var(--text-muted)">hollow=projected · line=today</span></div>
 <div class="card"><div id="tlsvg"></div></div>
 <div class="callout"><b>Enforcement in the timeline:</b> DHS-reported operations now appear on the Deploy track — e.g. the Jul 2026 World Cup human-trafficking crackdown (905 arrested, 180 rescued, agency-reported). The 2025 enforcement sequence still shows policy switch (Jan) preceding software (Apr) and appropriations (Jul): law and money followed policy.</div>
 <h2>Relationship: does law follow capability?</h2><div class="card"><div class="hbars" id="relbars"></div></div></div>

<div id="invest" class="hidden"><div class="tiles" id="i_tiles"></div><h2>Capital flows: disclosed vs announced pledge</h2><p class="note">Disclosed = ceilings, 10-K revenue, appropriations, closed rounds. Pledge = multi-year, milestone-gated. Never summed. Not investment advice.</p><div class="card"><div class="hbars" id="cfsplit"></div></div>
 <h2>Largest capital flows</h2><div class="card"><div class="hbars" id="cftop"></div></div><h2>Market size by domain <span class="note">(analyst forecasts; 2&ndash;3&times; variance)</span></h2><div class="card"><div class="hbars" id="mktdom"></div></div><h2>Investment thesis by domain</h2><div class="card" id="thesisList"></div></div>

<div id="lit" class="hidden"><div class="tiles" id="l_tiles"></div><h2>Cases by vendor / system</h2><div class="card"><div class="hbars" id="lvbars"></div></div>
 <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px"><div><h2>By status</h2><div class="card"><div class="hbars" id="lsbars"></div></div></div><div><h2>By jurisdiction</h2><div class="card"><div class="hbars" id="ljbars"></div></div></div></div>
 <h2>Case register <span id="lcount" style="color:var(--text-secondary);font-weight:400"></span></h2><p class="note">Not legal advice. Ongoing/appeal cases may change. Wrongdoing attributed only where a court/regulator so found. "organized-harassment" = Zersetzung-analogue addendum, kept separate from gov-cloud cases.</p><div class="card" style="max-height:60vh"><table class="dt" id="ltab2"></table></div></div>

<div id="cap" class="hidden"><div class="tiles" id="c_tiles"></div><h2>What the platforms do &mdash; capabilities by category</h2><div class="card"><div class="hbars" id="ccbars"></div></div>
 <h2>Capabilities by vendor</h2><div class="card"><div class="hbars" id="cvbars"></div></div>
 <h2>Capability register <span id="ccount" style="color:var(--text-secondary);font-weight:400"></span></h2><p class="note">What each platform/service technically does and its government mission use. Filter by category above.</p><div class="card" style="max-height:60vh"><table class="dt" id="ctab"></table></div></div>

<p class="foot">Independent research from public sources; informational only, not legal/investment advice. Names for identification; no affiliation/endorsement implied. Award/investment values mix ceilings, pledges &amp; projected savings. Enforcement figures are agency-reported (arrests are not convictions). Tier B/C not established fact. © 2026.</p>
</div><div id="tip"></div>`;
const SCRIPT_ID = "gov-cloud-report-script";

export default function GovCloudReport() {
  useEffect(() => {
    // React 18 StrictMode mounts effects twice in dev. An earlier version removed
    // the <script> on cleanup, which aborted the in-flight fetch before it ran and
    // left the report blank. So: never remove it, and key off its presence in the
    // DOM rather than a ref, which also survives navigating away and back.
    if (document.getElementById(SCRIPT_ID)) return;
    const s = document.createElement("script");
    s.id = SCRIPT_ID;
    s.src = "/reports/gov-cloud-report.js";
    s.async = false;
    document.body.appendChild(s);
  }, []);

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: CSS }} />
      <div className="gov-report w-full" dangerouslySetInnerHTML={{ __html: MARKUP }} />
    </>
  );
}
